export const WORKER_ENV = 'WORKER_ENV';
export const WORKER_REDIS_STORE_CLIENT = 'WORKER_REDIS_STORE_CLIENT';
export const WORKER_REDIS_QUEUE_CLIENT = 'WORKER_REDIS_QUEUE_CLIENT';
export const WORKER_SALE_STORE = 'WORKER_SALE_STORE';
export const WORKER_PG_POOL = 'WORKER_PG_POOL';
export const ORDERS_QUEUE_ADMIN = 'ORDERS_QUEUE_ADMIN';
export const ORDERS_BULL_WORKER = 'ORDERS_BULL_WORKER';
export const RECONCILIATION_STATE = 'RECONCILIATION_STATE';
